% Author: CatInCosmicSpace
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{diploma}[2020/06/01 Report template class]

\LoadClass{article}

\def\abstractLine{Выпускная квалификационная работа бакалавра состоит из}
\def\termsAndDefinitionsLine{В настоящей выпускной квалификационной работе бакалавра
применяют следующие термины с соответствующими определениями:}
\def\abbreviationsLine{В настоящей выпускной квалификационной работе бакалавра
применяют следующие сокращения и обозначения:}

\RequirePackage[T2A]{fontenc}
\RequirePackage[utf8]{inputenc}
\RequirePackage[russian]{babel}
\RequirePackage{hyphsubst}

\RequirePackage{01-base}
\RequirePackage{02-construction}
\RequirePackage{03-numbering}
\RequirePackage{04-section-numbering}
\RequirePackage{05-figures}
\RequirePackage{06-tables}
\RequirePackage{07-footnotes}
\RequirePackage{08-formulas}
\RequirePackage{09-cites}
\RequirePackage{10-titlepage}
\RequirePackage{11-performers}
\RequirePackage{12-abstract}
\RequirePackage{13-contents}
\RequirePackage{14-terms-and-definitions}
\RequirePackage{15-list-of-abbreviations}
\RequirePackage{16-references}
\RequirePackage{17-appendices}
\RequirePackage{18-extra}
\RequirePackage{19-counters}
\RequirePackage{20-listing}
\RequirePackage{21-math}
\RequirePackage{22-algorithms}

\makeglossaries
